############################################################################################
# Ledger Application Configuration
#
# This file can be used to override the default application YAML in:
#   src/resources/application.yml.
#
# For all other spring boot container properties, see:
# https://docs.spring.io/spring-boot/appendix/application-properties/index.html
############################################################################################

spring:
  ## Default datasource (insecure)
  datasource:
    url: jdbc:postgresql://localhost:26257/ledger?sslmode=disable
    username: root
    password:
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE

  ## Default datasource (secure)
#  datasource:
#    url: jdbc:postgresql://localhost:26257/ledger?sslmode=require
#    username: craig
#    password: cockroach
#    hikari:
#      transaction-isolation: TRANSACTION_SERIALIZABLE

  ## Alternative datasource (Cloud)
#  datasource:
#    url: jdbc:postgresql://valhalla-qzx.aws-eu-north-1.cockroachlabs.cloud:26257/ledger?sslmode=require
#    username: craig
#    password: cockroach
#    hikari:
#      transaction-isolation: TRANSACTION_SERIALIZABLE

application:
  ## Use pre-emptive locks when reading with the intent to write.
  # WARNING: It's imperative for correctness in READ_COMMITTED to set this to true.
  # If set to false, you may observe lost update (P4) anomalies under READ_COMMITTED.
  # Under SERIALIZABLE (1SR) however, correctness is never compromised but
  # locking may help to reduce contention.
  using-locks: true
  ## Ledger is I/O bound and uses JDK21 virtual threads rather than thread pools.
  task-executor:
    # A negative value denotes an unbounded amount of concurrent tasks.
    # For best performance on high-end machines, leave this value as-is.
    concurrency-limit: -1
  ## Sample period for time-series data points in graphs
  sample-period-seconds: 300
  ## Default account plan settings
  account-plan:
    # Number of accounts per city
    accounts-per-city: 5_000
    # Initial balance for user asset accounts (in local currency)
    initial-balance: 5000.00

## See "../src/resources/application.yml" for other settings.
