############################################################################################
# Ledger Application Configuration
#
# This file overrides the application configuration properties.
# For all spring boot container properties, see:
#  https://docs.spring.io/spring-boot/appendix/application-properties/index.html
############################################################################################

spring:
  ## Default datasource (insecure)
  datasource:
    url: jdbc:postgresql://localhost:26257/ledger?sslmode=disable
    username: root
    password:
    hikari:
      transaction-isolation: TRANSACTION_SERIALIZABLE

  ## Default datasource (secure)
#  datasource:
#    url: jdbc:postgresql://localhost:26257/ledger?sslmode=require
#    username: craig
#    password: cockroach
#    hikari:
#      transaction-isolation: TRANSACTION_SERIALIZABLE

  ## Alternative datasource (Cloud)
#  datasource:
#    url: jdbc:postgresql://valhalla-qzx.aws-eu-north-1.cockroachlabs.cloud:26257/ledger?sslmode=require
#    username: craig
#    password: cockroach
#    hikari:
#      transaction-isolation: TRANSACTION_SERIALIZABLE